### ISSUE TITLE
Updating on Debian via apt overwrites default.json AND local.json 

### ISSUE THREAD

**Issue by laryllian** [ONLYOFFICE/document-server-package#238]
**Do you want to request a *feature* or report a *bug*?**
A bug on Linux.

**What is the current behavior?**
Updating on Debian via apt overwrites /etc/onlyoffice/documentserver/local.json.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Just install, change the local.json and update.

**What is the expected behavior?**
default.json should be updated, but local.json should stay the same

**Did this work in previous versions of DocumentServer?**
Not sure.

**DocumentServer version:**
onlyoffice-documentserver v5.5.3-39

**Operating System:**
Debian GNU/Linux 10 (buster)

**Browser version:**
(not relevant)

Thank you for the good work.

**Comment by ShockwaveNN** [comment]
This issue is still unresolved, but I moving it to proper repo on behalf of[ this comment](https://github.com/ONLYOFFICE/document-server-package/issues/235#issuecomment-1020977921)

**Comment by adriangibanelbtactic** [comment]
My request is to change this default behaviour to what happens in most usual Debian packages. You define the local.json file as a conf file that your final user can modify in your package definition.

So when the package is updated if the user has modified that file a message similar to following one is asked to the final user.

```
Configuration file '/etc/onlyoffice/documentserver/local.json'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** local.json (Y/I/N/O/D/Z) [default=N] ? N
```

Thank you.

**Comment by ShockwaveNN** [comment]
This issie is resolved and will be fixed with next stable release (probably withing a month)

**Comment by ShockwaveNN** [comment]
DocumentServer v7.2.0 is released, this issue should be fixed
