### ISSUE TITLE
deb package configure fails with custom ds-port

### ISSUE THREAD

**Issue by Fantu** [ONLYOFFICE/document-server-package#294]
When a custom ds-port is setted package configure always fails for nginx restart failed for wrong configuration.
As saw the postinst change the port in the all virtual hosts causing issue after duplicate on the same port, in particular the internal service one that should remain to port 80.
I setted correctly as wrote in documentation, for example:
`echo onlyoffice-documentserver-ee onlyoffice/ds-port select 4444 | sudo debconf-set-selections`
From a fast look the issue is cause by the sed on all listen in the https://github.com/ONLYOFFICE/document-server-package/blob/master/deb/template/postinst.m4

As workaround for now after configure failing I comment service restart in postinst:
```
vi /var/lib/dpkg/info/onlyoffice-documentserver-ee.postinst
                #service supervisor restart >/dev/null 2>&1
                #service nginx restart >/dev/null 2>&1
```
I'll redo the configure that complete, after I'll fix the listen lines in ds.conf changing only the virtualhost for https and restarting the services.
postinst ds-port part should be fixed/improved and a possible improvements would be 2 additional different parameters (for example ds-port-http and ds-port-https) for change only http virtualhost and https virtualhost (for example I need only the https one) and the internal service one should remain always the same port FWIK
Thanks for any reply and sorry for my bad english.

**Comment by igwyd** [comment]
hello @Fantu, i checked installation onlyoffice-documentserver on ubuntu20.04 with custom ds port same as your ```echo onlyoffice-documentserver-ee onlyoffice/ds-port select 4444 | sudo debconf-set-selections``` and i didn't get an error. Please provide more information about your installation and your server version so we can reproduce the error and figure out how to fix it.

**Comment by Fantu** [comment]
thanks for the reply, strange that you not reproduced it, I always had it for what I remember (I didn't remember on what version I start use onlyoffice, 5.x probably) on both enterprise (on one server used by about thirty users from some months) and some community on all others.
are all debian 10 if I remember good.
`sed 's/\(listen .*:\)\([0-9]\{2,5\}\b\)\( default_server\)\?\(;\)/\1'${DS_PORT}'\3\4/' -i $DS_CONF`
in https://github.com/ONLYOFFICE/document-server-package/blob/master/deb/template/postinst.m4 should be the cause because change listen of all virtual hosts
anyway maybe on monday i will update 2 servers and I'll post the wrong config files due to that sed in postinst

**Comment by igwyd** [comment]
@Fantu i get it, using debconfig will change http port, not https. [Documentation](https://helpcenter.onlyoffice.com/installation/docs-community-install-ubuntu.aspx) has warning (in part _Changing the default ONLYOFFICE Docs port_) for this situation: 
```
Warning
If you want to change the ONLYOFFICE Docs protocol to HTTPS, do not change the port to 443, but use this instruction instead.
```
[this instruction](https://helpcenter.onlyoffice.com/server/linux/document/switch-to-https.aspx)

**Comment by Fantu** [comment]
https was already configured correctly and virtualhost is working, atleast until update that broke it.
above I also posted both the correct and working ds.conf and the broken one after the postint (see the paste.debian links)
it is also not good change it in that way and also change it in any case, debian package should change it only with new version and if there are users change (in my case done for the https) should manage the various possibilities
unfortunately in this period I am too busy and I also don't know how to create onlyoffice packages to test very quickly
sorry for my bad english

**Comment by igwyd** [comment]
Debconf should be used if you **only** change the HTTP port. As far as I can see from your config, you need to change protocol to the HTTPS with standart 443 or your custom port. Just return port 80 to debconf ```echo onlyoffice-documentserver onlyoffice/ds-port select 80 | sudo debconf-set-selections``` and HTTPS protocol and your custom port will remain after the update onlyoffice-documentserver without errors.
In other words, do not use debconf if you change the protocol to https, but follow [this instruction](https://helpcenter.onlyoffice.com/installation/docs-community-https-linux.aspx).

**Comment by Fantu** [comment]
tried the the workaround you posted `echo onlyoffice-documentserver onlyoffice/ds-port select 80 | sudo debconf-set-selections` and worked, thanks

**Comment by Rita-Bubnova** [comment]
I'll close this issue. Feel free to comment or reopen it if you got further questions.
